[package]
name = "bevy_tilemap"
version = "0.3.1"
authors = ["Joshua J. Bouw <dev@joshuajbouw.com>"]
edition = "2018"
description = "Tilemaps with chunks for the Bevy game engine, a simple-driven game engine and app framework"
repository = "https://github.com/joshuajbouw/bevy_tilemap"
license = "MIT"
keywords = ["game", "engine", "bevy", "tiles", "tilemap"]
categories = ["game-engines", "graphics", "gui"]
readme = "README.md"
documentation = "https://docs.rs/bevy_tilemap/latest/bevy_tilemap/"
exclude = ["assets/**/*", ".github/**/*", "doc/**/*"]

[package.metadata.docs.rs]
features = ["serialize", "types"]

[features]
default = ["png", "hdr"]

# crate
types = []

# physics
simd-stable = ["bevy_rapier2d/simd-stable"]
parallel = ["bevy_rapier2d/parallel"]

# render
hdr = ["bevy_render/hdr"]
png = ["bevy_render/png"]
dds = ["bevy_render/dds"]
tga = ["bevy_render/tga"]
jpeg = ["bevy_render/jpeg"]
# bmp = ["bevy_render/bmp"]

# serde
serialize = ["bevy_tilemap_types/serialize", "serde"]

[workspace]
members = ["library/*", "examples"]

[dependencies]
bevy_app = "0.4.0"
bevy_asset = "0.4.0"
bevy_core = "0.4.0"
bevy_ecs = "0.4.0"
bevy_log = "0.4.0"
bevy_math = "0.4.0"
bevy_rapier2d = "0.7.0"
bevy_render = "0.4.0"
bevy_reflect = "0.4.0"
bevy_sprite = "0.4.0"
bevy_tilemap_types = { path = "library/types", version = "0.1" }
bevy_transform = "0.4.0"
bevy_utils = "0.4.0"
bevy_window = "0.4.0"
bitflags = "1.2.1"
hexasphere = "3.1.0"
serde = { version = "1.0", features = ["derive"], optional = true }
